name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push Docker image
      run: |
        docker build -t nanda07/wisecow:latest .
        docker push nanda07/wisecow:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.20.0'

    - name: Create kubeconfig directory and config
      run: |
        mkdir -p ~/.kube
        echo "
        apiVersion: v1
        clusters:
        - cluster:
            certificate-authority-data: ${{ secrets.CA_CERT }}
            server: https://<minikube-cluster-endpoint>
          name: minikube
        contexts:
        - context:
            cluster: minikube
            user: minikube-user
          name: minikube
        current-context: minikube
        kind: Config
        preferences: {}
        users:
        - name: minikube-user
          user:
            client-certificate-data: ${{ secrets.CLIENT_CERT }}
            client-key-data: ${{ secrets.CLIENT_KEY }}" > ~/.kube/config

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
